### ISSUE TITLE
UBB to Markdown conversion plan

### ISSUE THREAD

**Issue by FransBouma** [FransBouma/HnD#5]
Currently, HnD uses UBB. Existing forums contain many posts with this markup. The new version should support Markdown as primary scheme. There's overlap in UBB and markdown and this gives a problem if both have to be supported. There's a way to support both: First convert UBB to Markdown (with extensions) and then parse the markdown to html. 

However this is problematic to maintain however and in the end not really sustainable: the future is markdown anyway, and it's expected that most new posts will have markdown as primary source if we make it the first choice. So the best way to make this work is to convert the existing messages offline to markdown using a specific xslt and store that markdown in the DB. Then re-publish the posts using the markdown parser. The same has to be done with the user signatures. 

There are a couple of problematic UBB statements supported which need further work in the Markdown parser. For markdown parser we'll use DocNet's markdown parser, which is based on MarkdownDeep and already has nice extensions which we can leverage without work. The markdown parser will be set to safemode, so only a sanitized set of HTML elements is allowed. As this list is defined in the parser, we can and need to adjust this if needed. 
## Conversion from UBB to Markdown for existing sites/forums

To convert the existing messages from UBB to Markdown, a standalone converter is created which will parse each existing message, convert it to markdown using xslt and store the resulting markdown into the DB again. It won't republish the message. This is done in the CLI tool `UbbToMarkdownConverter`. 

To convert smoothly to Markdown, some UBB statements are problematic and need additional markdown extensions or work. 

The problematic UBB statements are: 
- `[quote]`. This has to be handled with an extension (see below about the `@quote <nick> @end` extension). The parser is set to 'safe mode' so it will handle `<blockquote>` tags properly, they're a bit of a pain to type in, especially with a nickname as well. So they're supported, but the parser's shortcut, `@quote` is easier. 
- `[offtopic]`. This should be handled with a `@offtopic text @end` extension. 
- `[size]`. This is simply ignored, so the text is of the same size. 
- `[color]`. This is simply ignored, so the text is of the same color as other text. Users have to use bold/italic to emphasize on words
- Ordered and unordered list directives are all converted as simple unordered lists. 
- `[u]` is not supported in markdown, we'll ignore the formatting and the text is used as-is.
- `[s]` is not supported in markdown, we'll add an extension for that (`~~`)

### Smileys
Our custom UBB parser recognizes any :) etc. as a smiley of a given type and replaces that with an image. The markdown parser has to be extended to support smileys. The current UBB parser is a bit loose in parsing smileys, as `:p1` will match with the `:P` smiley even though there's no whitespace following :p. 

- smiley tokens from the UBB have to be converted to emoji strings, as defined in https://github.com/WebpageFX/emoji-cheat-sheet.com. This is the set of emojis used on github and e.g. slack, so lots of people are familiar with them.  
- The Markdown parser has to be updated to support emoji's and also the shortcuts. It has to be strict regarding when a shortcut matches, so `:p1` should not match `:p`. 

Furthermore, the Markdown parser has to support emoji tokens in the form `:name:`: the `name` is then matched with the set of known/supported emojis and if found it's used to render an emoji HTML tag (see https://github.com/WebpageFX/emoji-cheat-sheet.com) otherwise it's ignored. 

For editing, we can use: https://github.com/franverona/jemoji 
It's tempting to use a js-based converter for emoji strings: it will release us from the parsing of emoji strings which are ever evolving. The problem is however that these visualizers don't understand the context of the string they're converting. This means that the string `:)` in a code block will be converted to a smiley. The problem of `:p1` therefore isn't solved. 

So the visualizers won't work, we need server-side emoji parsing in the markdown. For editing we can use the jemoji library as it's an excellent performing library with exactly what we need. The visualization of the emoji in the editor isn't done but that's OK: there's no wysiwyg visualization in the editor anyway.

The emoji parsing then is also able to convert e.g. `:!` to `:blush:`. To parse this quickly we need a mapping list between emoji strings and their images. This is easily to obtain from https://github.com/WebpageFX/emoji-cheat-sheet.com. These are the emoji's used by many people/apps and the least ugly ones. Twitter released theirs too, 'twemoji', but these are using unicode characters. While a good way to get uniformity, it's not usable from an editor's perspective, as we have to translate the cheatsheet ones to these unicode characters, which is a pain. Therefore we'll ignore them at first. 

Parsing the strings into the parse target isn't hard: once the ':' token is seen in plain text inside the markdown parser, it can scan for the old ones (if they are followed by EOL or whitespace). If the text doesn't match the old ones, the next `:` is searched by simply searching for identifier + "_" and "-" which should be followed by another `:`. If so, we've found an emoji, otherwise we ignore it. 

#### Parse target.
It's either <img> tags, or css like with this: http://ellekasai.github.io/twemoji-awesome/ As twemoji works with unicode characters and we work with cheat-sheet names, they're not compatible. The Twemoji-awesome project could mitigate that but it's discontinued. As many apps use the cheatsheet icons, we'll do that too, so we'll generate <img> tags. 

### DocNet's markdown deep parser

We'll leverage DocNet's markdownDeep parser, though some features in there have to be disabled:
- The extension for heading permalinks should be removed/disabled. 
- Collecting h2 permalinks isn't needed
- The include statement has to be disabled. 

The following extensions have to be added: 
- To quote text: `@quote [nick]` text `@end`. As with all current extensions `@quote` has to be at the start of a new line. This is markdown and some elements start at the beginning of a line, the same goes with `@end`. `@quote` should be emitting a `<blockquote>` so it's easy to nest them inside each other.  `[quote]`'s argument is optional, so `@quote` should have its argument as optional too. If a nickname is specified in the markdown, this is rendered as: `<blockquote><span class="quote-nickname">Nickname wrote:</span> quoted text` etc. The `<blockquote>` element is then formatted with CSS.
- To handle emojis / smileys (see above): parsing of `:)`, `:p` etc. to emojis. 
- To handle offtopic text: `@offtopic` text `@end`. For `@offtopic` too, it should be possible to write it anywhere in the text. It is rendered as `<div class="offtopic">text</div>`. As with other extensions, `@offtopic` has to placed at the beginning of a line.
- To handle strikethrough, we follow the github flavored markdown and use `~~text~~`. It is rendered as `<s>text</s>`. 

The following changes have to be made:
- The sanitized set of tags has to be cleared. No tags are allowed, as the problem is that they could ruin the html output: if a block html tag isn't closed or e.g. a `<b>` tags isn't closed, things will bleed through to other posts.  

As statements can be nested, the parser has to be checked whether it can deal with nested `@end` statements for example. If not, we have to either adjust this, e.g. with a stack, or use different syntax (which is less preferable). 

The stylesheet for the forum has to include the CSS defined in DocNet for e.g. alerts and tables. 
## Signatures

In current versions of HnD, signatures can contain a limited set of UBB elements. In the new version, signatures can only contain plain text. This is a simple way to avoid a complicated issue: markdown parses everything and it's hard to limit that output. 
## Tasks
- [x] Create standalone converter to convert existing messages in UBB to Markdown. 
- [x] Add Markdown parser from DocNet 
- [x] Solve signature problem described above
- [x] Add `@quote` extension to markdown parser
- [x] Add `@offtopic` extension to markdown parser
- [x] Add `~~` extension to markdown parser
- [x] Add emoji/smiley extension to markdown parser
- [x] Sanitize markdown allowed html tags to not allow anything. 
- [x] Create editor view / controller / model 
- [x] Connect editor with Markdown parser, update HnD.Utility to use Markdown Parser instead of UBB parser. 
- [x] Remove UBB parser from HnD main, and add it to UbbToMarkdownConverter, as it's needed there. 
- [x] Move UbbToMarkdownConverter to separate solution.
- [x] Move 'TextParser' from SD.HnD.Utility to UbbToMarkdownConverter. 
- [x] Remove Message.MessageTextAsXml as it's no longer needed.

**Comment by FransBouma** [comment]
Everything now implemented. No client-side emoji lookup for now, as all lookup tooling for client side sucks at the moment with respect to text areas. 

Closed.
